### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by govindchari** [govindchari/TrajUtils.jl#1]
- [ ] Add single shooting for trajectory (impulsive, foh, single dilation, multiple dilation)
- [ ] Add rendezvous unit test (multiple dilation, impulsive, test single shooting performance)
- [ ] Add PDG unit test (single dilation, foh)
